---
WATCHES_PATH: "{{ playbook_dir }}/watches.yaml"
MODEL_SAMPLE_PATH: "{{ playbook_dir }}/config/samples/{{ WATCH_DATA.group | split('.') | first }}_v1_{{ CRD_NAME | lower }}.yaml"
MODEL_VALUES_PATH: "{{ playbook_dir }}/roles/crd-vars/vars/values/values-{{ CRD_NAME }}.yaml"
MODEL_SPEC_PATH: "{{ OPERATOR_PREFIX }}/smart-data-models/{{ DOMAIN_NAME | default('Smart Cities') | replace(' ', '') }}/dataModel.{{SUBMODULE_SHORT_NAME | default('Transportation') }}/{{ MODEL_NAME | default('Unknown') }}/model.yaml"
MODEL_SPEC: "{{ lookup('file', MODEL_SPEC_PATH, errors='ignore') | from_yaml | default('') }}"
MODEL_DESCRIPTION: "{{ description | default(FIWARE_SMART_DATA_MODELS[(DOMAIN_NAME | default('Smart Cities'))].SUBMODULES[(SUBMODULE_SHORT_NAME | default('Transportation'))].MODELS[(MODEL_NAME | default('Unknown'))].MODEL_DESCRIPTION) | indent(4, False) | default('') }}"
