---
- name: Delete a KeycloakAuthorization resource from OpenShift
  hosts: localhost
  connection: local
  pre_tasks:
    - fail:
        msg: Variable crd_path is not defined
      when: crd_path is not defined
    - name: "Query KeycloakAuthorization"
      set_fact:
        crd_complete: "{{ (lookup('file', crd_path) | from_yaml) }}"
      vars:
        CRD_NAME: KeycloakAuthorization
      when: crd_path is defined
    - name: "Set crd var"
      set_fact:
        crd: "{{ crd_complete.spec }}"
      when: crd_path is defined
    - name: "Set name var"
      set_fact:
        ansible_operator_meta_name: "{{ crd_complete.metadata.name }}"
      when:
        crd_path is defined and ansible_operator_meta_name is not defined
    - name: "Set namespace var"
      set_fact:
        ansible_operator_meta_namespace: "{{ crd_complete.metadata.namespace }}"
      when:
        crd_path is defined and ansible_operator_meta_namespace is not defined
  roles:
    - crd-vars
    - delete-keycloakauthorization
  vars:
    CRD_NAME: KeycloakAuthorization
    ansible_operator_meta:
      name: "{{ ansible_operator_meta_name }}"
      namespace: "{{ ansible_operator_meta_namespace }}"
    verify_connections: false
