# permissions for end users to edit keycloakauthorizations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: keycloakauthorization-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: keycloak-permissions-operator
    app.kubernetes.io/part-of: keycloak-permissions-operator
    app.kubernetes.io/managed-by: kustomize
  name: keycloakauthorization-editor-role
rules:
- apiGroups:
  - keycloak.nerc.mghpcc.org
  resources:
  - keycloakauthorizations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - keycloak.nerc.mghpcc.org
  resources:
  - keycloakauthorizations/status
  verbs:
  - get
