---
- name: Install a {{ CRD_NAME }} resource from OpenShift
  hosts: localhost
  connection: local
  gather_facts: false
  pre_tasks:
    - fail:
        msg: Variable crd_path is not defined
      when: crd_path is not defined
    - name: "Query {{ CRD_NAME }}"
      set_fact:
        crd_complete: "\{\{ (lookup('file', crd_path) | from_yaml) \}\}"
      vars:
        CRD_NAME: {{ CRD_NAME }}
      when: crd_path is defined
    - name: "Set crd var"
      set_fact:
        crd: "\{\{ crd_complete.spec \}\}"
      when: crd_path is defined
    - name: "Set name var"
      set_fact:
        ansible_operator_meta_name: "\{\{ crd_complete.metadata.name \}\}"
      when:
        crd_path is defined and ansible_operator_meta_name is not defined
    - name: "Set namespace var"
      set_fact:
        ansible_operator_meta_namespace: "\{\{ crd_complete.metadata.namespace \}\}"
      when:
        crd_path is defined and ansible_operator_meta_namespace is not defined
  roles:
    - crd-vars
    - apply-{{ CRD_NAME | lower }}
  vars:
    CRD_NAME: {{ CRD_NAME }}
    ansible_operator_meta:
      name: "\{\{ ansible_operator_meta_name \}\}"
      namespace: "\{\{ ansible_operator_meta_namespace \}\}"
