---

- name: Query permissions
  ansible.builtin.uri:
    url: "{{ AUTH_BASE_URL }}/admin/realms/{{ REALM_ID }}/clients/{{ CLIENT_ID }}/authz/resource-server/permission?first={{ loop_data_first }}&max={{ loop_data_max }}"
    validate_certs: "{{ values.validateCerts }}"
    headers:
      Content-Type: "application/json"
      Accept: "application/json"
      Authorization: "Bearer {{ AUTH_TOKEN.json.access_token }}"
  register: QUERY_PERMISSIONS
  ignore_errors: "{{  DELETE_CRD is defined and DELETE_CRD }}"
- name: Remove permission {{ permission.name }}
  community.general.keycloak_authz_permission:
    name: "{{ permission.name }}"
    state: absent
    realm: "{{ REALM_ID }}"
    client_id: "{{ CLIENT_ID }}"
    permission_type: "{{ permission.type }}"
    auth_keycloak_url: "{{ AUTH_BASE_URL }}"
    auth_username: "{{ AUTH_USERNAME }}"
    auth_password: "{{ AUTH_PASSWORD }}"
    auth_realm: master
    validate_certs: "{{ values.validateCerts }}"
  loop: "{{ QUERY_PERMISSIONS.json }}"
  loop_control:
    loop_var: permission
  when: DELETE_CRD is defined and DELETE_CRD and permission.name in PERMISSION_NAMES or values.cleanupUndefinedAuthorizations and permission.name not in PERMISSION_NAMES
  ignore_errors: "{{  DELETE_CRD is defined and DELETE_CRD }}"
- name: Update loop_data
  set_fact:
    loop_data_first: "{{ (loop_data_first | int) + (loop_data_max | int) }}"
- name: Loop delete-permission-loop
  include_role: 
    name: delete-permission-loop
  when: (QUERY_PERMISSIONS.json | length) == (loop_data_max | int)
  ignore_errors: "{{  DELETE_CRD is defined and DELETE_CRD }}"
