---
# tasks file for KeycloakAuthorization

- name: "Query KeycloakAuthorization"
  set_fact:
    crd: "{{ (lookup('file', crd_path) | from_yaml).spec }}"
  ignore_errors: true
  vars:
    CRD_NAME: KeycloakAuthorization
  when: crd_path is defined
- name: "Query KeycloakAuthorization"
  set_fact:
    crd: "{{ query('kubernetes.core.k8s', kind='KeycloakAuthorization', resource_name=ansible_operator_meta.name, namespace=ansible_operator_meta.namespace)[0].spec }}"
  ignore_errors: true
  vars:
    CRD_NAME: KeycloakAuthorization
  when: crd_path is not defined
- name: Run Ansible role crd-vars
  include_role:
    name: crd-vars
  vars:
    CRD_NAME: KeycloakAuthorization
- name: "Verify KeycloakAuthorization exists"
  fail:
    msg: |-
      You need to deploy a KeycloakAuthorization to OpenShift before running this playbook.
  vars:
    CRD_NAME: KeycloakAuthorization
  when: crd is not defined
- name: Run Ansible role apply-keycloakauthorization
  include_role:
    name: apply-keycloakauthorization
  vars:
    CRD_NAME: KeycloakAuthorization
  when: values.managementState == 'Managed'
